"""Type stubs for the pixelsrc package."""

__version__: str

# -- Tier 1: Stateless functions (to be implemented in PY-3..PY-7) --

def render_to_png(pxl: str) -> bytes: ...
def render_to_rgba(pxl: str) -> RenderResult: ...
def validate(pxl: str) -> list[str]: ...
def list_sprites(pxl: str) -> list[str]: ...
def list_palettes(pxl: str) -> list[str]: ...
def parse(pxl: str) -> list[dict]: ...
def format_pxl(pxl: str) -> str: ...
def parse_color(color_str: str) -> str: ...
def generate_ramp(from_color: str, to_color: str, steps: int) -> list[str]: ...

def import_png(
    path: str,
    name: str | None = None,
    max_colors: int | None = None,
) -> ImportResult: ...

def import_png_analyzed(
    path: str,
    name: str | None = None,
    max_colors: int | None = None,
    confidence: float | None = None,
    hints: bool | None = None,
    shapes: bool | None = None,
    detect_upscale: bool | None = None,
    detect_outlines: bool | None = None,
    dither_handling: str | None = None,
) -> ImportResult: ...

# -- Result types --

class RenderResult:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def pixels(self) -> bytes: ...
    @property
    def warnings(self) -> list[str]: ...

class ImportResult:
    @property
    def name(self) -> str: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def palette(self) -> dict[str, str]: ...
    @property
    def analysis(self) -> dict | None: ...
    def to_pxl(self) -> str: ...
    def to_jsonl(self) -> str: ...

# -- Tier 2: Stateful API (to be implemented in PY-8) --

class Registry:
    def __init__(self) -> None: ...
    def load(self, pxl: str) -> None: ...
    def load_file(self, path: str) -> None: ...
    def sprites(self) -> list[str]: ...
    def palettes(self) -> list[str]: ...
    def render(self, name: str) -> RenderResult: ...
    def render_to_png(self, name: str) -> bytes: ...
    def render_all(self) -> dict[str, bytes]: ...
